services:
  - type: web
    name: tedtalk-extractor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT web_app:app
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        generateValue: true

